### ISSUE TITLE
"Add an icon with list" can not show complete

### ISSUE THREAD

**Issue by liyofx** [keremciu/sketch-use-fontawesome#10]
![Uploading image.png…](http://wx4.sinaimg.cn/mw1024/a18895abgy1fcxn74epg3j20xy0mwq6l.jpg)

**Comment by keremciu** [comment]
hello @idock 

I wrote an information on readme file of this repository 
`This plugin is not developing no more. You can use https://github.com/keremciu/sketch-iconfont plugin, its a maintainable version.`
