### ISSUE TITLE
Plugin doesn't work after updating to Sketch Version 45 (43475)

### ISSUE THREAD

**Issue by konmouz** [keremciu/sketch-use-fontawesome#13]
The plugin seems to be inactive. Selecting a new icon or replacing an existing one is not possible. However, already existing icons are still ok (display the intended icon).

Note: Issue remains after restarting Sketch and rebooting. (macOS Sierra - 10.12.5)

**Comment by keremciu** [comment]
hello @konmouz 

this plugin is not developing anymore as you can read on readme file

```This plugin is not developing no more. You can use https://github.com/keremciu/sketch-iconfont plugin, its a maintainable version.```

**Comment by konmouz** [comment]
cheers @keremciu
