### ISSUE TITLE
Not working for the new version of sketch. 45

### ISSUE THREAD

**Issue by ChrissN** [keremciu/sketch-use-fontawesome#14]
Many plugins have stopped working for this version and this is one of them :( are you going to update to match this version? Thanks.

**Comment by nikolayzaytsev** [comment]
Confirmed

**Comment by keremciu** [comment]
@ChrissN @nikolayzaytsev 

hello guys, sorry about that but

this plugin is not developing anymore as you can read on readme file

This plugin is not developing no more. You can use https://github.com/keremciu/sketch-iconfont plugin, its a maintainable version.
