### ISSUE TITLE
All icons are not working

### ISSUE THREAD

**Issue by Agrollemund** [keremciu/sketch-use-fontawesome#4]
Hi guys,

I'm a big fan of you plugin but unfortunately i got an issue using all the icons. When i'm browsing the icons in the combobox some icons aren't loading i have  question marks instead 
![screen shot 2015-10-26 at 11 20 47](https://cloud.githubusercontent.com/assets/6607078/10725293/a16b472a-7bd3-11e5-9742-3726fcb49488.png)
. I'm have the latest version of the 4.4.0. 

Thanks in advance.

**Comment by Agrollemund** [comment]
Since sketch 3.4, i can only open once the plugin. I need to restart sketch in order for the plugin to work.

**Comment by crashlab** [comment]
You have an outdated font installed.
Go to your system Font Book and Uninstall the Font Awesome Family font.
Then, download the updated font version from here: http://fontawesome.io/assets/font-awesome-4.5.0.zip
Unzip it and click on the "ttf" file to install it.
Problem will be solved

**Comment by Sacdaniel** [comment]
Hello,

Having trouble getting the plugin working on Sketch Version 41.1 (35376). It was working on Sketch 40.3 before I updated. I go into adding a new icon, I select one, insert, and nothing displays on the artboard (or even in the layers panel). 

Please help. Thanks!

[sketch_fontawesome.mov.zip](https://github.com/keremciu/sketch-use-fontawesome/files/635091/sketch_fontawesome.mov.zip)
