### ISSUE TITLE
Can't work in Sketch v39.1

### ISSUE THREAD

**Issue by junezhang** [keremciu/sketch-use-fontawesome#6]
HI, @keremciu 
The fontawesome plugin is very cool.
When I used it in Sketch v39.1, it can't work well.
Can't add an icon to the page, could you please have a check, thanks.

**Comment by luisameglio** [comment]
Same problem here

**Comment by thcottin** [comment]
Same here

**Comment by luisameglio** [comment]
I started using this plug-in https://github.com/keremciu/sketch-iconfont it works pretty good..

**Comment by keremciu** [comment]
@junezhang @luisameglio @thcottin sorry guys but I've an information on readme file of this repository, "This plugin is not developing no more. You can use https://github.com/keremciu/sketch-iconfont plugin, its a maintainable version." @luisameglio is right, you need to use iconfont plugin not this one :/ this plugin involved to that
