### ISSUE TITLE
Icon not appearing after pressing "+ Add/Change Icon"

### ISSUE THREAD

**Issue by iamwillow** [keremciu/sketch-use-fontawesome#7]
I apologize if I am missing a step. 
1. Installed this plugin through Sketch Toolbox
2. Downloaded the font onto my computer
3. Went to Plugins > Font Awesome > Add an Icon with List
4. Clicked on an icon
5. Pressed "+ Add/Change Icon" link
6. ~~ Icon did not appear anywhere

Oooh, I just read "This plugin is not developing no more." 
That's really sad.  The UI of this was great.

**Comment by keremciu** [comment]
@iamwillow Nice to hear your comments about the UI ✌️ but you know performance is so important for a plugin that is why I changed the UI :(
