### ISSUE TITLE
Plugin not working on Sketch | Version 41.1 (35376)

### ISSUE THREAD

**Issue by Sacdaniel** [keremciu/sketch-use-fontawesome#9]
Hello,

Having trouble getting the plugin working on Sketch | Version 41.1 (35376). It was working on Version 40.3 before I updated. I go into adding a new icon, I select one, insert, and nothing displays on the artboard (or even in the layers panel - see video).

Please help. Thanks!

[sketch_fontawesome.mov.zip](https://github.com/keremciu/sketch-use-fontawesome/files/635098/sketch_fontawesome.mov.zip)

**Comment by keremciu** [comment]
hey @Sacdaniel you should install the new version of this plugin 

https://github.com/keremciu/sketch-iconfont

this is deprecated
